security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email  # Utilisation de l'email comme identifiant

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users

            form_login:
                login_path: app_login                 # Route d'affichage du formulaire
                check_path: /login_check              # Symfony intercepte cette route
                enable_csrf: true
                csrf_token_id: authenticate
                success_handler: App\Security\LoginSuccessHandler  # Redirection personnalisée
                username_parameter: email             # Correspond au name="email" du formulaire
                password_parameter: password          # Correspond au name="password" du formulaire

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800                      # 7 jours
                path: /
                always_remember_me: false

            logout:
                path: /logout
                target: homepage
                enable_csrf: true

            entry_point: form_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
