security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email  # Utilisation de l'email comme identifiant

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users

            form_login:
                login_path: security_login
                check_path: security_login
                enable_csrf: true
                default_target_path: blog_index
                username_parameter: email
                password_parameter: password

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

            logout:
                target: homepage
                enable_csrf: true

            entry_point: form_login

        admin:
            pattern: ^/admin
            provider: database_users
            lazy: true

            # 🔒 Pas de form_login ici, car /login est géré par le firewall "main"
            logout:
                target: homepage
                enable_csrf: true

            # ❌ Supprimé : entry_point: form_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
