<?php

namespace ContainerXujzwlG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllerPhpControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BookControllerPhpController' shared autowired service.
     *
     * @return \App\Controller\BookControllerPhpController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BookControllerPhpController.php';

        $container->services['App\\Controller\\BookControllerPhpController'] = $instance = new \App\Controller\BookControllerPhpController();

        $instance->setContainer(($container->privates['.service_locator.l0cG.ww'] ?? $container->load('get_ServiceLocator_L0cG_WwService'))->withContext('App\\Controller\\BookControllerPhpController', $container));

        return $instance;
    }
}
