<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_NL5kSSLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.NL5kSSL' shared service.
     *
     * @return \App\Repository\BookRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\BlogController::livres()": the $bookRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\BookRepository".');
    }
}
