<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DS0yNhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d_s0yNh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d_s0yNh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.AcfYa9Y.App\\Controller\\Admin\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\Admin\\BlogController::new' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\Admin\\BlogController::new()', 'getBlogControllernewService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.95r6gX0.App\\Controller\\Admin\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.1vNE1Q3.App\\Controller\\Admin\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.1vNE1Q3.App\\Controller\\Admin\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\Admin\\BlogController::commentDelete' => ['privates', '.service_locator.Fbxi6sJ.App\\Controller\\Admin\\BlogController::commentDelete()', 'getBlogControllercommentDeleteService', true],
            'App\\Controller\\Admin\\BlogController::profile' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\Admin\\BlogController::profile()', 'getBlogControllerprofileService', true],
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => ['privates', '.service_locator.5FanY8e.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.mtjqjIT.App\\Controller\\BlogController::index()', 'getBlogControllerindex2Service', true],
            'App\\Controller\\BlogController::indexByTag' => ['privates', '.service_locator.mtjqjIT.App\\Controller\\BlogController::indexByTag()', 'getBlogControllerindexByTagService', true],
            'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.95r6gX0.App\\Controller\\BlogController::postShow()', 'getBlogControllerpostShowService', true],
            'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.jFa5KmS.App\\Controller\\BlogController::commentNew()', 'getBlogControllercommentNewService', true],
            'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.80cKC8..App\\Controller\\BlogController::commentForm()', 'getBlogControllercommentFormService', true],
            'App\\Controller\\BlogController::search' => ['privates', '.service_locator.jcYtTcg.App\\Controller\\BlogController::search()', 'getBlogControllersearchService', true],
            'App\\Controller\\BlogController::livres' => ['privates', '.service_locator.g8eWwQs', 'get_ServiceLocator_G8eWwQsService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.l6i3pzs.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.g7oipAF.App\\Controller\\UserController::changePassword()', 'getUserControllerchangePasswordService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.AcfYa9Y.App\\Controller\\Admin\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\Admin\\BlogController:new' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\Admin\\BlogController::new()', 'getBlogControllernewService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.95r6gX0.App\\Controller\\Admin\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.1vNE1Q3.App\\Controller\\Admin\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.1vNE1Q3.App\\Controller\\Admin\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\Admin\\BlogController:commentDelete' => ['privates', '.service_locator.Fbxi6sJ.App\\Controller\\Admin\\BlogController::commentDelete()', 'getBlogControllercommentDeleteService', true],
            'App\\Controller\\Admin\\BlogController:profile' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\Admin\\BlogController::profile()', 'getBlogControllerprofileService', true],
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => ['privates', '.service_locator.5FanY8e.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.mtjqjIT.App\\Controller\\BlogController::index()', 'getBlogControllerindex2Service', true],
            'App\\Controller\\BlogController:indexByTag' => ['privates', '.service_locator.mtjqjIT.App\\Controller\\BlogController::indexByTag()', 'getBlogControllerindexByTagService', true],
            'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.95r6gX0.App\\Controller\\BlogController::postShow()', 'getBlogControllerpostShowService', true],
            'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.jFa5KmS.App\\Controller\\BlogController::commentNew()', 'getBlogControllercommentNewService', true],
            'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.80cKC8..App\\Controller\\BlogController::commentForm()', 'getBlogControllercommentFormService', true],
            'App\\Controller\\BlogController:search' => ['privates', '.service_locator.jcYtTcg.App\\Controller\\BlogController::search()', 'getBlogControllersearchService', true],
            'App\\Controller\\BlogController:livres' => ['privates', '.service_locator.g8eWwQs', 'get_ServiceLocator_G8eWwQsService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.l6i3pzs.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.g7oipAF.App\\Controller\\UserController::changePassword()', 'getUserControllerchangePasswordService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::new' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\Admin\\BlogController::commentDelete' => '?',
            'App\\Controller\\Admin\\BlogController::profile' => '?',
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::indexByTag' => '?',
            'App\\Controller\\BlogController::postShow' => '?',
            'App\\Controller\\BlogController::commentNew' => '?',
            'App\\Controller\\BlogController::commentForm' => '?',
            'App\\Controller\\BlogController::search' => '?',
            'App\\Controller\\BlogController::livres' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:new' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\Admin\\BlogController:commentDelete' => '?',
            'App\\Controller\\Admin\\BlogController:profile' => '?',
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:indexByTag' => '?',
            'App\\Controller\\BlogController:postShow' => '?',
            'App\\Controller\\BlogController:commentNew' => '?',
            'App\\Controller\\BlogController:commentForm' => '?',
            'App\\Controller\\BlogController:search' => '?',
            'App\\Controller\\BlogController:livres' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
        ]);
    }
}
