<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllercommentFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.80cKC8..App\Controller\BlogController::commentForm()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.80cKC8..App\\Controller\\BlogController::commentForm()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', 'App\\Entity\\User', 'getUserService', true],
            'post' => ['privates', 'App\\Entity\\Post', 'getPostService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'post' => 'App\\Entity\\Post',
        ]))->withContext('App\\Controller\\BlogController::commentForm()', $container);
    }
}
