<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllercommentDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fbxi6sJ.App\Controller\Admin\BlogController::commentDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fbxi6sJ.App\\Controller\\Admin\\BlogController::commentDelete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', 'App\\Entity\\Comment', 'getCommentService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Admin\\BlogController::commentDelete()', $container);
    }
}
