<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1vNE1Q3.App\Controller\Admin\BlogController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.1vNE1Q3'] ?? $container->load('get_ServiceLocator_1vNE1Q3Service'));

        if (isset($container->privates['.service_locator.1vNE1Q3.App\\Controller\\Admin\\BlogController::edit()'])) {
            return $container->privates['.service_locator.1vNE1Q3.App\\Controller\\Admin\\BlogController::edit()'];
        }

        return $container->privates['.service_locator.1vNE1Q3.App\\Controller\\Admin\\BlogController::edit()'] = $a->withContext('App\\Controller\\Admin\\BlogController::edit()', $container);
    }
}
