<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerprofileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WkfvUVe.App\Controller\Admin\BlogController::profile()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WkfvUVe'] ?? $container->load('get_ServiceLocator_WkfvUVeService'));

        if (isset($container->privates['.service_locator.WkfvUVe.App\\Controller\\Admin\\BlogController::profile()'])) {
            return $container->privates['.service_locator.WkfvUVe.App\\Controller\\Admin\\BlogController::profile()'];
        }

        return $container->privates['.service_locator.WkfvUVe.App\\Controller\\Admin\\BlogController::profile()'] = $a->withContext('App\\Controller\\Admin\\BlogController::profile()', $container);
    }
}
