<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerindex2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mtjqjIT.App\Controller\BlogController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mtjqjIT.App\\Controller\\BlogController::index()'] = ($container->privates['.service_locator.mtjqjIT'] ?? $container->load('get_ServiceLocator_MtjqjITService'))->withContext('App\\Controller\\BlogController::index()', $container);
    }
}
