<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestrictedWordsValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\RestrictedWordsValidator' shared autowired service.
     *
     * @return \App\Validator\RestrictedWordsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/RestrictedWordsValidator.php';

        return $container->privates['App\\Validator\\RestrictedWordsValidator'] = new \App\Validator\RestrictedWordsValidator();
    }
}
