<?php

namespace ContainerZ9ujQDi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_Translator_CacheWarmer_TranslationsCacheWarmerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.translator.cache_warmer.translations_cache_warmer' shared service.
     *
     * @return \Symfony\UX\Translator\CacheWarmer\TranslationsCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-translator/src/CacheWarmer/TranslationsCacheWarmer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-translator/src/TranslationsDumper.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-translator/src/MessageParameters/Extractor/ExtractorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-translator/src/MessageParameters/Extractor/MessageParametersExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-translator/src/MessageParameters/Extractor/IntlMessageParametersExtractor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-translator/src/MessageParameters/Printer/TypeScriptMessageParametersPrinter.php';

        return $container->privates['ux.translator.cache_warmer.translations_cache_warmer'] = new \Symfony\UX\Translator\CacheWarmer\TranslationsCacheWarmer(($container->services['translator'] ?? self::getTranslatorService($container)), new \Symfony\UX\Translator\TranslationsDumper((\dirname(__DIR__, 3).'/translations'), new \Symfony\UX\Translator\MessageParameters\Extractor\MessageParametersExtractor(), new \Symfony\UX\Translator\MessageParameters\Extractor\IntlMessageParametersExtractor(), new \Symfony\UX\Translator\MessageParameters\Printer\TypeScriptMessageParametersPrinter(), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem())));
    }
}
