# ✅ Import des routes des contrôleurs avec attributs
controllers:
    resource: ../src/Controller/
    type: attribute

# ✅ Route du tableau de bord admin
admin_dashboard:
    path: /{_locale}/admin
    controller: App\Controller\Admin\DashboardController::index
    requirements:
        _locale: en|fr
    methods: [GET]

# ✅ Blog par tag
blog_index_tag:
    path: /{_locale}/blog/tag/{tagName}
    controller: App\Controller\BlogController::indexByTag
    requirements:
        _locale: en|fr
        tagName: .*

# ✅ Route de test contact
contact_test:
    path: /{_locale}/contact/controller/test
    controller: App\Controller\ContactController::test
    requirements:
        _locale: en|fr
