# Définir la route pour la page d'accueil avec la gestion des locales
homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig
        _locale: '%app.locale%'
    requirements:
        _locale: en|fr

# Définir les routes pour les contrôleurs personnalisés, avec un préfixe de locale
controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: '%app.locale%'

# Route du tableau de bord admin avec locale
admin_dashboard:
    path: /{_locale}/admin
    controller: App\Controller\Admin\DashboardController::index
    requirements:
        _locale: en|fr
    methods: [GET]

# Route blog avec tag (sans doublon de _locale)
blog_index_tag:
    path: /{_locale}/blog/tag/{tagName}
    controller: App\Controller\BlogController::indexByTag
    requirements:
        _locale: en|fr
        tagName: .*

# Route test contact
contact_test:
    path: /{_locale}/contact/controller/test
    controller: App\Controller\ContactController::test
    requirements:
        _locale: en|fr