<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwSsXV8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwSsXV8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQwSsXV8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQwSsXV8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQwSsXV8\App_KernelDevDebugContainer([
    'container.build_hash' => 'QwSsXV8',
    'container.build_id' => 'c8ace122',
    'container.build_time' => 1744285582,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwSsXV8');
